'use client';

import React, { useEffect, useMemo, useRef, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ErrorMessage } from '../components/ui/ErrorMessage';


interface CounterItem {
  value: number;
  label: string;
}

interface CountersData {
  success: boolean;
  data?: Record<string, CounterItem>;
  error?: string;
}

const heroSlides = [
  {
    id: 'access',
    title: 'Access Codes',
    description:
      'Access Code is a special code generated by a corporate account for any test and given to a candidate or employee. Managers can filter candidates by test result, saving interview costs for those who do not match the position criteria.',
    image: '/landing/acc_mac.png',
  },
  {
    id: 'credits',
    title: 'Credits',
    description:
      'Credits allow registered users to take paid tests. One credit is used for one paid test. Free tests are available without credits.',
    image: '/landing/credits.png',
  },
  {
    id: 'result',
    title: 'Result Code',
    description:
      'Result Code is generated after a quiz is completed. Results are bound to the code and can be shared on social networks or added to a CV. Enter the Result Code on the home page to view the quiz results.',
    image: '/landing/res.png',
  },
  {
    id: 'private',
    title: 'Private Account',
    description:
      'Purchase quizzes and take them at any convenient moment. After completion we generate a Result Code for you. All Result Codes are stored in your profile and can be shared or added to your CV.',
    image: '/landing/ua2.png',
  },
  {
    id: 'corporate',
    title: 'Corporate Account',
    description:
      'Generate Access Codes for any test and give them to candidates or employees. Check proficiency level before an interview or during corporate review processes.',
    image: '/landing/ca2.png',
  },
];

const featureCards = [
  {
    icon: 'coins',
    title: 'Save money',
    description:
      'Want a certificate in computer science but unsure if you are ready? Cut expenses, test yourself on EvaluateMe.IT and be prepared.',
  },
  {
    icon: 'database',
    title: 'Quiz results database',
    description:
      'Every passed quiz stores your result and score in the database. Access or share your success by copying a unique result code.',
  },
  {
    icon: 'speed',
    title: 'Performance and cross platform',
    description:
      'Evaluate yourself from PC, Mac, tablet or smartphone. Navigation is fast on every device and you will not waste time waiting for results.',
  },
  {
    icon: 'headphone',
    title: 'Access codes for the testee',
    description:
      'Generate an Access Code and send it to a candidate before an interview to filter out unsuitable matches and save money on unsuccessful interviews.',
  },
  {
    icon: 'certificate',
    title: 'Confirm your knowledge',
    description:
      'Confirm your knowledge with an EvaluateMe certificate: pass a quiz, copy your result code and add it to your CV.',
  },
  {
    icon: 'share',
    title: 'Social networks',
    description:
      'Take part in the competition and share your results to social networks. Prove to everyone that you are the best.',
  },
];

const showcaseItems = [
  {
    id: 'access-code',
    title: 'Access code',
    intro:
      'If you have a corporate account, you can generate Access Codes for any test and give them to potential candidates or employees.',
    details: [
      'Log in with your corporate account.',
      'Go to your personal dashboard.',
      'Type the testee name and email.',
      'Select the technology and test set for the quiz.',
      'Select the number of questions and the time allowed.',
      'Generate the access code and click “Use code”.',
      'When the code is generated it appears in the dashboard with an inactive status. After you configure it properly, activate it manually; one credit is then taken from the account.',
      'The activation code is sent to the testee and can be used to take the quiz.',
      'If the code is no longer relevant, mark it as Archived; it will be stored and accessible through the filter menu.',
    ],
    image: '/landing/Mockup-Generated-by-Dunnnk.png',
    imagePosition: 'right',
  },
  {
    id: 'accounts',
    title: 'Accounts',
    intro: 'There are two types of accounts: Personal account and Corporate account.',
    details: [
      'With a personal account, the user can purchase quizzes and take them at any convenient moment. After the quiz we generate a Result Code. All Result Codes are stored in the profile and can be shared or added to a CV.',
      'With a corporate account, the user can generate Access Codes for any test and give them to candidates or employees to check proficiency level before an interview or during corporate processes.',
    ],
    image: '/landing/2acc.png',
    imagePosition: 'left',
  },
  {
    id: 'quiz',
    title: 'Quiz process',
    intro:
      'The testee can take a quiz and the results will be saved and bound to a Result Code. There are free and paid quizzes; one credit is taken from the account after the first answer is selected and confirmed in a paid quiz.',
    details: [
      'While answering, the testee must answer all questions within the time limit. The number of questions and time limit are configurable.',
      'The testee can navigate through questions and mark some for postponed answering.',
      'When time is up, the quiz is finalized automatically and unanswered questions are marked incorrect.',
      'The testee can also finalize the quiz manually at any time.',
      'Each correct answer gives 1 point. Choosing 1 correct and 1 incorrect answer gives 0.5 points; 1 correct and 3 incorrect gives 0.25 points.',
    ],
    image: '/landing/acc-codes.png',
    imagePosition: 'right',
  },
  {
    id: 'results',
    title: 'Quiz results',
    intro:
      'The quiz result page displays the percentage of correct answers, as well as incorrect and partially correct answers.',
    details: [
      'If questions are grouped by area, results show total and per-section percentages.',
      'For a personal account each result is stored on the “Test History” page.',
      'For a corporate account, all results are bound to Access Codes and can be viewed on the “Dashboard” page.',
    ],
    image: '/landing/result-codes.png',
    imagePosition: 'left',
  },
];

const counterIcons: Record<string, JSX.Element> = {
  technologies: (
    <svg viewBox="0 0 24 24" className="w-8 h-8" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="M12 14l9-5-9-5-9 5 9 5z" />
      <path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
    </svg>
  ),
  users: (
    <svg viewBox="0 0 24 24" className="w-8 h-8" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
    </svg>
  ),
  questions: (
    <svg viewBox="0 0 24 24" className="w-8 h-8" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  testsPassed: (
    <svg viewBox="0 0 24 24" className="w-8 h-8" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
    </svg>
  ),
};

function CountUp({ target, duration = 1500 }: { target: number; duration?: number }): JSX.Element {
  const [value, setValue] = useState(0);
  const ref = useRef<HTMLSpanElement>(null);

  useEffect(() => {
    let raf = 0;
    let start: number | null = null;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          const step = (timestamp: number) => {
            if (start === null) start = timestamp;
            const progress = Math.min((timestamp - start) / duration, 1);
            setValue(Math.floor(progress * target));
            if (progress < 1) {
              raf = requestAnimationFrame(step);
            }
          };
          raf = requestAnimationFrame(step);
          observer.disconnect();
        }
      },
      { threshold: 0.5 },
    );

    if (ref.current) observer.observe(ref.current);
    return () => {
      observer.disconnect();
      cancelAnimationFrame(raf);
    };
  }, [target, duration]);

  return <span ref={ref}>{value.toLocaleString()}</span>;
}

function Icon({ name }: { name: string }): JSX.Element {
  switch (name) {
    case 'coins':
      return (
        <svg viewBox="0 0 24 24" className="w-10 h-10" fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      );
    case 'database':
      return (
        <svg viewBox="0 0 24 24" className="w-10 h-10" fill="none" stroke="currentColor" strokeWidth="1.5">
          <ellipse cx="12" cy="5" rx="9" ry="3" />
          <path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3" />
          <path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5" />
        </svg>
      );
    case 'speed':
      return (
        <svg viewBox="0 0 24 24" className="w-10 h-10" fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M13 10V3L4 14h7v7l9-11h-7z" />
        </svg>
      );
    case 'headphone':
      return (
        <svg viewBox="0 0 24 24" className="w-10 h-10" fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
        </svg>
      );
    case 'certificate':
      return (
        <svg viewBox="0 0 24 24" className="w-10 h-10" fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
        </svg>
      );
    case 'share':
      return (
        <svg viewBox="0 0 24 24" className="w-10 h-10" fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
        </svg>
      );
    default:
      return (
        <svg viewBox="0 0 24 24" className="w-10 h-10" fill="none" stroke="currentColor" strokeWidth="1.5">
          <circle cx="12" cy="12" r="9" />
        </svg>
      );
  }
}


function ResultCodeLookupSection(): JSX.Element {
  const [code, setCode] = useState('');

  function handleSubmit(): void {
    const trimmed = code.trim();
    if (!trimmed) return;
    window.location.href = `/result?code=${encodeURIComponent(trimmed)}`;
  }

  return (
    <section id="result-code" className="bg-bg-primary py-16 sm:py-20 lg:py-28 border-y border-border">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-8 sm:mb-10">
          <p className="font-mono text-xs uppercase tracking-[0.12em] text-accent mb-3">Result Lookup</p>
          <h2 className="font-display text-3xl sm:text-4xl font-bold text-text-primary">View a quiz result</h2>
          <p className="mt-3 text-text-secondary font-body">Enter a Result Code to see the quiz result.</p>
        </div>
        <div className="panel accent p-6 sm:p-8 space-y-5">
          <label htmlFor="home-result-code" className="label-mono">Result code</label>
          <form
            onSubmit={(e) => { e.preventDefault(); handleSubmit(); }}
            className="flex gap-3"
          >
            <input
              id="home-result-code"
              type="text"
              value={code}
              onChange={(e) => { setCode(e.target.value); }}
              placeholder="Enter result code" // e.g. USR-...
              className="input-field flex-1"
            />
            <button
              type="submit"
              disabled={code.trim().length === 0}
              className="btn-primary disabled:opacity-50"
            >
              View result
            </button>
          </form>
        </div>
      </div>
    </section>
  );
}

export default function HomePage(): JSX.Element {
  const [activeSlide, setActiveSlide] = useState(0);
  const [calcTab, setCalcTab] = useState<'user' | 'corporate'>('user');
  const [otherPrice, setOtherPrice] = useState(10);
  const [testCount, setTestCount] = useState(10);
  const [averagePrice, setAveragePrice] = useState(20);
  const [interviewers, setInterviewers] = useState(2);
  const [duration, setDuration] = useState(2);
  const [totalInterviews, setTotalInterviews] = useState(10);
  const [failedInterviews, setFailedInterviews] = useState(5);
  const [expandedShowcase, setExpandedShowcase] = useState<Record<string, boolean>>({});
  const [counters, setCounters] = useState<Record<string, CounterItem> | null>(null);
  const [myPrice, setMyPrice] = useState<number | null>(null);
  const [contactStatus, setContactStatus] = useState<'idle' | 'sending' | 'sent' | 'error'>('idle');
  const [contactError, setContactError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/counters')
      .then((res) => res.json())
      .then((payload: CountersData) => {
        if (payload.success && payload.data) setCounters(payload.data);
      })
      .catch(() => {
        setCounters({
          technologies: { value: 18, label: 'Technologies and languages' },
          users: { value: 1240, label: 'Registered users' },
          questions: { value: 6535, label: 'Total test questions' },
          testsPassed: { value: 8932, label: 'Passed tests' },
        });
      });

    fetch('/api/credit-price')
      .then((res) => res.json())
      .then((payload: { success?: boolean; data?: { price?: number } }) => {
        if (payload.success && typeof payload.data?.price === 'number') {
          setMyPrice(payload.data.price);
        }
      })
      .catch(() => {
        setMyPrice(3);
      });
  }, []);

  useEffect(() => {
    const timer = setInterval(() => {
      setActiveSlide((prev) => (prev + 1) % heroSlides.length);
    }, 6000);
    return () => clearInterval(timer);
  }, []);

  const userSavings = useMemo(() => {
    const pricePerTest = myPrice ?? 3;
    const myTotal = pricePerTest * testCount;
    const otherTotal = otherPrice * testCount;
    return { myTotal, otherTotal, savings: Math.max(0, otherTotal - myTotal), pricePerTest };
  }, [otherPrice, testCount, myPrice]);

  const corporateSavings = useMemo(() => {
    const interviewCost = averagePrice * interviewers * duration;
    const saved = interviewCost * failedInterviews;
    const totalSpent = interviewCost * totalInterviews;
    return { saved, totalSpent };
  }, [averagePrice, interviewers, duration, totalInterviews, failedInterviews]);

  function toggleShowcase(id: string): void {
    setExpandedShowcase((prev) => ({ ...prev, [id]: !prev[id] }));
  }

  async function handleContactSubmit(event: React.FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault();
    setContactStatus('sending');
    setContactError(null);

    const formData = new FormData(event.currentTarget);
    const body = {
      name: String(formData.get('name') ?? ''),
      email: String(formData.get('email') ?? ''),
      phone: String(formData.get('phone') ?? ''),
      message: String(formData.get('message') ?? ''),
    };

    try {
      const response = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      const result = (await response.json()) as { success?: boolean; error?: string };
      if (!response.ok || !result.success) {
        throw new Error(result.error || 'Failed to send message');
      }
      setContactStatus('sent');
      event.currentTarget.reset();
    } catch (err) {
      setContactStatus('error');
      setContactError(err instanceof Error ? err.message : 'Failed to send message');
    }
  }

  return (
    <div className="flex flex-col">
      {/* Hero slider */}
      <section id="home" className="relative border-b border-border overflow-hidden bg-bg-primary">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24 lg:py-32 w-full">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
            <div>
              <p className="font-mono text-sm uppercase tracking-[0.12em] text-accent mb-4 sm:mb-6">
                EvaluateMe.IT v3
              </p>
              <h1 className="font-display text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold text-text-primary leading-[1.05] tracking-tight text-balance">
                Prove what you know.
              </h1>
              <div className="mt-6 sm:mt-8 min-h-[7rem]">
                <h2 className="font-display text-2xl sm:text-3xl font-bold text-text-primary">
                  {heroSlides[activeSlide].title}
                </h2>
                <p className="mt-3 text-lg text-text-secondary font-body leading-relaxed">
                  {heroSlides[activeSlide].description}
                </p>
              </div>

            </div>
            <div className="relative aspect-[4/3] w-full">
              {heroSlides.map((slide, index) => (
                <div
                  key={slide.id}
                  className={`absolute inset-0 transition-opacity duration-700 ${
                    index === activeSlide ? 'opacity-100 z-10' : 'opacity-0 z-0'
                  }`}
                >
                  <Image
                    src={slide.image}
                    alt={slide.title}
                    fill
                    className="object-contain"
                    priority={index === 0}
                  />
                </div>
              ))}
            </div>
          </div>
          <div className="mt-10 flex justify-center gap-3">
            {heroSlides.map((_, index) => (
              <button
                key={index}
                type="button"
                onClick={() => setActiveSlide(index)}
                className={`w-3 h-3 rounded-full border border-border-strong transition-colors ${
                  index === activeSlide ? 'bg-accent border-accent' : 'bg-bg-secondary hover:bg-bg-tertiary'
                }`}
                aria-label={`Show slide ${index + 1}`}
              />
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="bg-bg-secondary py-16 sm:py-20 lg:py-28">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto mb-12 sm:mb-16">
            <p className="font-mono text-xs uppercase tracking-[0.12em] text-accent mb-3">Why EvaluateMe.it</p>
            <h2 className="font-display text-3xl sm:text-4xl font-bold text-text-primary">About EvaluateMe.it</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-px bg-border border border-border">
            {featureCards.map((card) => (
              <div
                key={card.title}
                className="group bg-bg-primary p-8 sm:p-10 transition-colors duration-200 hover:bg-bg-secondary"
              >
                <div className="text-accent mb-5">
                  <Icon name={card.icon} />
                </div>
                <h3 className="font-display text-xl font-bold text-text-primary group-hover:text-accent transition-colors">
                  {card.title}
                </h3>
                <p className="mt-3 text-text-secondary font-body leading-relaxed">{card.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Calculator */}
      <section id="calculator" className="bg-bg-primary py-16 sm:py-20 lg:py-28 border-y border-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto mb-12 sm:mb-16">
            <p className="font-mono text-xs uppercase tracking-[0.12em] text-accent mb-3">Pricing</p>
            <h2 className="font-display text-3xl sm:text-4xl font-bold text-text-primary">Calculator</h2>
          </div>

          <div className="border border-border bg-bg-secondary">
            <div className="flex flex-col sm:flex-row border-b border-border">
              <button
                type="button"
                onClick={() => setCalcTab('user')}
                className={`flex-1 px-6 py-4 font-mono text-sm uppercase tracking-wider transition-colors ${
                  calcTab === 'user'
                    ? 'bg-bg-primary text-text-primary border-b-2 border-accent'
                    : 'bg-bg-secondary text-text-secondary hover:text-text-primary'
                }`}
              >
                For user account
              </button>
              <button
                type="button"
                onClick={() => setCalcTab('corporate')}
                className={`flex-1 px-6 py-4 font-mono text-sm uppercase tracking-wider transition-colors ${
                  calcTab === 'corporate'
                    ? 'bg-bg-primary text-text-primary border-b-2 border-accent'
                    : 'bg-bg-secondary text-text-secondary hover:text-text-primary'
                }`}
              >
                For corporate account
              </button>
            </div>

            <div className="p-6 sm:p-10 lg:p-12 bg-bg-primary">
              {calcTab === 'user' ? (
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16">
                  <div className="space-y-8">
                    <p className="text-text-secondary font-body">
                      Getting ready for a job interview? Want to prepare for an international test? Calculate the
                      price for taking tests and your potential savings.
                    </p>

                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="label-mono">EvaluateMe price</label>
                        <div className="text-2xl font-display font-bold text-text-primary">
                          ${userSavings.pricePerTest.toLocaleString()}
                        </div>
                      </div>
                      <div>
                        <label className="label-mono">Other test price</label>
                        <div className="text-2xl font-display font-bold text-text-primary">${otherPrice}</div>
                      </div>
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <label className="label-mono mb-0">Other test price</label>
                        <span className="font-mono text-sm text-accent">${otherPrice}</span>
                      </div>
                      <input
                        type="range"
                        min={5}
                        max={250}
                        step={1}
                        value={otherPrice}
                        onChange={(e) => setOtherPrice(Number(e.target.value))}
                        className="w-full accent-accent"
                      />
                      <div className="flex justify-between mt-2 font-mono text-xs text-text-muted">
                        <span>$5</span>
                        <span>$125</span>
                        <span>$250</span>
                      </div>
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <label className="label-mono mb-0">Test count</label>
                        <span className="font-mono text-sm text-accent">{testCount}</span>
                      </div>
                      <input
                        type="range"
                        min={1}
                        max={500}
                        step={1}
                        value={testCount}
                        onChange={(e) => setTestCount(Number(e.target.value))}
                        className="w-full accent-accent"
                      />
                      <div className="flex justify-between mt-2 font-mono text-xs text-text-muted">
                        <span>1</span>
                        <span>250</span>
                        <span>500</span>
                      </div>
                    </div>
                  </div>

                  <div className="border border-border bg-bg-secondary p-8 sm:p-10 flex flex-col justify-center">
                    <p className="font-mono text-xs uppercase tracking-[0.12em] text-accent mb-4">Comparison</p>
                    <div className="space-y-6">
                      <div className="flex items-center justify-between border-b border-border pb-4">
                        <span className="font-body text-text-secondary">Other proposition</span>
                        <span className="font-display text-2xl font-bold text-text-primary">
                          ${userSavings.otherTotal.toLocaleString()}
                        </span>
                      </div>
                      <div className="flex items-center justify-between border-b border-border pb-4">
                        <span className="font-body text-text-secondary">EvaluateMe proposition</span>
                        <span className="font-display text-2xl font-bold text-accent">
                          ${userSavings.myTotal.toLocaleString()}
                        </span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="font-body text-text-secondary">Savings</span>
                        <span className="font-display text-3xl font-bold text-success">
                          ${userSavings.savings.toLocaleString()}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16">
                  <div className="space-y-8">
                    <p className="text-text-secondary font-body">
                      What is your hiring success rate? Calculate your expenses per interview and how much you can save
                      by filtering candidates with Access Codes.
                    </p>

                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <label className="label-mono mb-0">Average price for 1h of 1 interviewer</label>
                        <span className="font-mono text-sm text-accent">${averagePrice}</span>
                      </div>
                      <input
                        type="range"
                        min={5}
                        max={100}
                        step={1}
                        value={averagePrice}
                        onChange={(e) => setAveragePrice(Number(e.target.value))}
                        className="w-full accent-accent"
                      />
                      <div className="flex justify-between mt-2 font-mono text-xs text-text-muted">
                        <span>$5</span>
                        <span>$50</span>
                        <span>$100</span>
                      </div>
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <label className="label-mono mb-0">Interviewers count</label>
                        <span className="font-mono text-sm text-accent">{interviewers}</span>
                      </div>
                      <input
                        type="range"
                        min={1}
                        max={4}
                        step={1}
                        value={interviewers}
                        onChange={(e) => setInterviewers(Number(e.target.value))}
                        className="w-full accent-accent"
                      />
                      <div className="flex justify-between mt-2 font-mono text-xs text-text-muted">
                        <span>1</span>
                        <span>4</span>
                      </div>
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <label className="label-mono mb-0">Interview duration (hours)</label>
                        <span className="font-mono text-sm text-accent">{duration}h</span>
                      </div>
                      <input
                        type="range"
                        min={1}
                        max={3}
                        step={0.5}
                        value={duration}
                        onChange={(e) => setDuration(Number(e.target.value))}
                        className="w-full accent-accent"
                      />
                      <div className="flex justify-between mt-2 font-mono text-xs text-text-muted">
                        <span>1h</span>
                        <span>2h</span>
                        <span>3h</span>
                      </div>
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <label className="label-mono mb-0">Total interviews per month</label>
                        <span className="font-mono text-sm text-accent">{totalInterviews}</span>
                      </div>
                      <input
                        type="range"
                        min={1}
                        max={50}
                        step={1}
                        value={totalInterviews}
                        onChange={(e) => setTotalInterviews(Number(e.target.value))}
                        className="w-full accent-accent"
                      />
                      <div className="flex justify-between mt-2 font-mono text-xs text-text-muted">
                        <span>1</span>
                        <span>25</span>
                        <span>50</span>
                      </div>
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <label className="label-mono mb-0">Unsuccessful interviews</label>
                        <span className="font-mono text-sm text-accent">{failedInterviews}</span>
                      </div>
                      <input
                        type="range"
                        min={0}
                        max={50}
                        step={1}
                        value={failedInterviews}
                        onChange={(e) => setFailedInterviews(Number(e.target.value))}
                        className="w-full accent-accent"
                      />
                      <div className="flex justify-between mt-2 font-mono text-xs text-text-muted">
                        <span>0</span>
                        <span>25</span>
                        <span>50</span>
                      </div>
                    </div>
                  </div>

                  <div className="border border-border bg-bg-secondary p-8 sm:p-10 flex flex-col justify-center">
                    <p className="font-mono text-xs uppercase tracking-[0.12em] text-accent mb-4">Savings</p>
                    <div className="space-y-6">
                      <div className="flex items-center justify-between border-b border-border pb-4">
                        <span className="font-body text-text-secondary">Monthly interview cost</span>
                        <span className="font-display text-2xl font-bold text-text-primary">
                          ${corporateSavings.totalSpent.toLocaleString()}
                        </span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="font-body text-text-secondary">Money saved with Access Codes</span>
                        <span className="font-display text-3xl font-bold text-success">
                          ${corporateSavings.saved.toLocaleString()}
                        </span>
                      </div>
                      <p className="text-sm text-text-secondary font-body mt-4">
                        Access Codes help filter out mismatched candidates before the interview, so every avoided
                        unsuccessful interview is direct savings.
                      </p>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* Showcase */}
      <section className="bg-bg-primary py-16 sm:py-20 lg:py-28">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto mb-12 sm:mb-16">
            <p className="font-mono text-xs uppercase tracking-[0.12em] text-accent mb-3">How it works</p>
            <h2 className="font-display text-3xl sm:text-4xl font-bold text-text-primary">Using the site</h2>
          </div>
          <div className="space-y-16 lg:space-y-24">
            {showcaseItems.map((item) => (
              <div
                key={item.id}
                className={`grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-center ${
                  item.imagePosition === 'left' ? 'lg:flex-row-reverse' : ''
                }`}
              >
                <div className={item.imagePosition === 'left' ? 'lg:order-2' : ''}>
                  <h3 className="font-display text-2xl sm:text-3xl font-bold text-text-primary mb-4">{item.title}</h3>
                  <p className="text-text-secondary font-body leading-relaxed mb-6">{item.intro}</p>
                  <div
                    className={`overflow-hidden transition-all duration-300 ${
                      expandedShowcase[item.id] ? 'max-h-[40rem]' : 'max-h-0'
                    }`}
                  >
                    <ul className="list-disc list-inside space-y-2 text-text-secondary font-body marker:text-accent">
                      {item.details.map((detail, index) => (
                        <li key={index}>{detail}</li>
                      ))}
                    </ul>
                  </div>
                  <button
                    type="button"
                    onClick={() => toggleShowcase(item.id)}
                    className="mt-6 inline-flex items-center font-mono text-sm uppercase tracking-wider text-accent hover:text-accent-hover transition-colors"
                  >
                    {expandedShowcase[item.id] ? 'Read Less' : 'Read More'}
                    <span className="ml-2">{expandedShowcase[item.id] ? '−' : '+'}</span>
                  </button>
                </div>
                <div className={item.imagePosition === 'left' ? 'lg:order-1' : ''}>
                  <div className="relative aspect-[4/3] w-full border border-border bg-bg-secondary">
                    <Image src={item.image} alt={item.title} fill className="object-contain p-4" />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Counters */}
      <section className="bg-text-primary text-inverted-primary py-16 sm:py-20 lg:py-28">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-px bg-inverted-border border border-inverted-border">
            {counters &&
              Object.entries(counters).map(([key, counter]) => (
                <div
                  key={key}
                  className="bg-text-primary p-8 sm:p-10 text-center flex flex-col items-center"
                >
                  <div className="text-inverted-accent mb-4">{counterIcons[key]}</div>
                  <h3 className="font-display text-3xl sm:text-4xl font-bold text-inverted-primary">
                    <CountUp target={counter.value} />
                  </h3>
                  <p className="mt-2 font-mono text-xs uppercase tracking-wider text-inverted-secondary">
                    {counter.label}
                  </p>
                </div>
              ))}
          </div>
        </div>
      </section>

      {/* Result Code Lookup */}
      <ResultCodeLookupSection />

      {/* Contact */}
      <section id="contact" className="bg-bg-secondary py-16 sm:py-20 lg:py-28 border-y border-border">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10 sm:mb-12">
            <p className="font-mono text-xs uppercase tracking-[0.12em] text-accent mb-3">Contact</p>
            <h2 className="font-display text-3xl sm:text-4xl font-bold text-text-primary">Get in Touch</h2>
          </div>

          {contactStatus === 'sent' ? (
            <div className="border border-success bg-bg-primary p-8 text-center">
              <h3 className="font-display text-xl font-bold text-success mb-2">Message sent</h3>
              <p className="text-text-secondary font-body">Thank you for reaching out. We will get back to you soon.</p>
              <button
                type="button"
                onClick={() => setContactStatus('idle')}
                className="mt-6 btn-secondary"
              >
                Send another message
              </button>
            </div>
          ) : (
            <form onSubmit={(event) => void handleContactSubmit(event)} className="bg-bg-primary border border-border p-6 sm:p-10 space-y-6">
              {contactError && <ErrorMessage message={contactError} />}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <label className="block">
                  <span className="label-mono">Firstname *</span>
                  <input name="name" type="text" required minLength={2} maxLength={20} className="input-field" placeholder="Please enter your firstname" />
                </label>
                <label className="block">
                  <span className="label-mono">Lastname *</span>
                  <input name="surname" type="text" required minLength={2} maxLength={20} className="input-field" placeholder="Please enter your lastname" />
                </label>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <label className="block">
                  <span className="label-mono">Email *</span>
                  <input name="email" type="email" required className="input-field" placeholder="Please enter your email" />
                </label>
                <label className="block">
                  <span className="label-mono">Phone</span>
                  <input name="phone" type="tel" className="input-field" placeholder="Please enter your phone" />
                </label>
              </div>
              <label className="block">
                <span className="label-mono">Message *</span>
                <textarea name="message" required rows={4} className="input-field" placeholder="Please leave us a message" />
              </label>
              <div className="flex items-center justify-between gap-4 flex-col sm:flex-row">
                <p className="text-sm text-text-muted font-body">* These fields are required.</p>
                <button type="submit" disabled={contactStatus === 'sending'} className="btn-primary">
                  {contactStatus === 'sending' ? 'Sending…' : 'Send message'}
                </button>
              </div>
            </form>
          )}
        </div>
      </section>

      {/* Feature index */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16 lg:py-20 w-full">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-px bg-border border border-border">
          {[
            {
              number: '01',
              title: 'Technologies',
              description: 'Browse the catalog and pick a skill to evaluate.',
              href: '/technologies',
            },
            {
              number: '02',
              title: 'Health',
              description: 'Check API and database status in real time.',
              href: '/health',
            },
            {
              number: '03',
              title: 'Join',
              description: 'Log in or sign up to track your progress.',
              href: '/login',
            },
          ].map((item) => (
            <Link
              key={item.href}
              href={item.href}
              className="group bg-bg-primary p-6 sm:p-8 transition-colors duration-200 hover:bg-bg-secondary"
            >
              <span className="font-mono text-xs text-text-muted">{item.number}</span>
              <h2 className="mt-4 font-display text-xl sm:text-2xl font-bold text-text-primary group-hover:text-accent transition-colors">
                {item.title}
              </h2>
              <p className="mt-2 text-text-secondary font-body">{item.description}</p>
            </Link>
          ))}
        </div>
      </section>
    </div>
  );
}
