export interface CountryOption {
  value: string;
  label: string;
  flag: string;
}

export const COUNTRY_OPTIONS: CountryOption[] = [
  { value: 'UA', label: 'Ukraine', flag: '🇺🇦' },
  { value: 'US', label: 'United States', flag: '🇺🇸' },
  { value: 'GB', label: 'United Kingdom', flag: '🇬🇧' },
  { value: 'CA', label: 'Canada', flag: '🇨🇦' },
  { value: 'DE', label: 'Germany', flag: '🇩🇪' },
  { value: 'FR', label: 'France', flag: '🇫🇷' },
  { value: 'IT', label: 'Italy', flag: '🇮🇹' },
  { value: 'ES', label: 'Spain', flag: '🇪🇸' },
  { value: 'PL', label: 'Poland', flag: '🇵🇱' },
  { value: 'NL', label: 'Netherlands', flag: '🇳🇱' },
  { value: 'BE', label: 'Belgium', flag: '🇧🇪' },
  { value: 'CZ', label: 'Czech Republic', flag: '🇨🇿' },
  { value: 'PT', label: 'Portugal', flag: '🇵🇹' },
  { value: 'SE', label: 'Sweden', flag: '🇸🇪' },
  { value: 'NO', label: 'Norway', flag: '🇳🇴' },
  { value: 'DK', label: 'Denmark', flag: '🇩🇰' },
  { value: 'FI', label: 'Finland', flag: '🇫🇮' },
  { value: 'CH', label: 'Switzerland', flag: '🇨🇭' },
  { value: 'AT', label: 'Austria', flag: '🇦🇹' },
  { value: 'AU', label: 'Australia', flag: '🇦🇺' },
  { value: 'JP', label: 'Japan', flag: '🇯🇵' },
  { value: 'KR', label: 'South Korea', flag: '🇰🇷' },
  { value: 'IN', label: 'India', flag: '🇮🇳' },
  { value: 'BR', label: 'Brazil', flag: '🇧🇷' },
  { value: 'MX', label: 'Mexico', flag: '🇲🇽' },
  { value: 'AR', label: 'Argentina', flag: '🇦🇷' },
  { value: 'ZA', label: 'South Africa', flag: '🇿🇦' },
  { value: 'TR', label: 'Turkey', flag: '🇹🇷' },
  { value: 'IL', label: 'Israel', flag: '🇮🇱' },
  { value: 'AE', label: 'United Arab Emirates', flag: '🇦🇪' },
  { value: 'SA', label: 'Saudi Arabia', flag: '🇸🇦' },
  { value: 'SG', label: 'Singapore', flag: '🇸🇬' },
  { value: 'NZ', label: 'New Zealand', flag: '🇳🇿' },
  { value: 'IE', label: 'Ireland', flag: '🇮🇪' },
  { value: 'GR', label: 'Greece', flag: '🇬🇷' },
  { value: 'HU', label: 'Hungary', flag: '🇭🇺' },
  { value: 'RO', label: 'Romania', flag: '🇷🇴' },
  { value: 'SK', label: 'Slovakia', flag: '🇸🇰' },
  { value: 'SI', label: 'Slovenia', flag: '🇸🇮' },
  { value: 'HR', label: 'Croatia', flag: '🇭🇷' },
  { value: 'BG', label: 'Bulgaria', flag: '🇧🇬' },
  { value: 'RS', label: 'Serbia', flag: '🇷🇸' },
  { value: 'LT', label: 'Lithuania', flag: '🇱🇹' },
  { value: 'LV', label: 'Latvia', flag: '🇱🇻' },
  { value: 'EE', label: 'Estonia', flag: '🇪🇪' },
  { value: 'GE', label: 'Georgia', flag: '🇬🇪' },
  { value: 'AM', label: 'Armenia', flag: '🇦🇲' },
  { value: 'AZ', label: 'Azerbaijan', flag: '🇦🇿' },
  { value: 'KZ', label: 'Kazakhstan', flag: '🇰🇿' },
  { value: 'BY', label: 'Belarus', flag: '🇧🇾' },
  { value: 'MD', label: 'Moldova', flag: '🇲🇩' },
  { value: 'UZ', label: 'Uzbekistan', flag: '🇺🇿' },
  { value: 'KG', label: 'Kyrgyzstan', flag: '🇰🇬' },
  { value: 'TJ', label: 'Tajikistan', flag: '🇹🇯' },
  { value: 'TM', label: 'Turkmenistan', flag: '🇹🇲' },
];
